# 2 level, 3 factor, full factorial DOE creator

*Updated 8/26/24*

The codes create Excel spreadsheets for a 2-level, 3-factor, full factorial experiment.  The Excel files are saved in /content.



After running the set up codes, either modify the code block#2 directly or use the interactive interface at code block#4

In [1]:
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output
import numpy as np
import pandas as pd
import itertools
import math
import statsmodels.api as sm
#
def number_to_binary(number, length):
  """Converts a number to its binary representation with a specified length.

  Args:
    number: The number to convert to binary.
    length: The desired length of the binary string.

  Returns:
    A string representing the binary form of the number with the given length.
  """
  binary_string = format(number, '0' + str(length) + 'b')
  return binary_string

#
def linear_mapping(vector,old_range,new_range):
  return (vector-old_range[0])/(old_range[1]-old_range[0])*(new_range[1]-new_range[0])+new_range[0]
#
def create_2level_full_factorial_design(factor_num, replication,randomize,center_point):
    # Create a 2-level full factorial design
    # factor_num, replication are integers, return an array of coded experiment plan
    combo_num=2**factor_num
    combo=np.arange(1,combo_num+1)
    total_num=combo_num*replication
    if center_point:
      total_num=total_num+replication+1
    plan=np.zeros((total_num,factor_num+1))
    for j in range (replication):
      if randomize:
        combo=np.random.permutation(combo)
      design=np.zeros((combo_num,factor_num))
      for i in range(combo_num):
        number =combo[i]-1
        binary_string = number_to_binary(number, factor_num)
        run = [int(bit) for bit in binary_string]
        design[i,:]=run
      design = design*2-1
      merged_array = np.column_stack((combo, design))
      if center_point:
        plan[j*combo_num+1*(j+1):(j+1)*combo_num+1*(j+1),:]=merged_array
      else:
        plan[j*combo_num:(j+1)*combo_num,:]=merged_array
    return plan
  #
def map_factors_to_ranges(factors, factor_ranges,plan_arr):
  arr=plan_arr[:,1:]
  mapped_arr=np.zeros((len(arr),len(factors)))
  #print(arr)
  for i in range(len(factors)):
    mapped_arr[:,i]=linear_mapping(arr[:,i],[-1,1],factor_ranges[i])
  #print(mapped_arr)
  plan_arr=np.column_stack((plan_arr[:,0],mapped_arr))
  return plan_arr


This is the place you input the factors and their levels for the design.  It creates an Excel spreadsheet for a coded 2-level, 3-factor, full factorial design.

In [2]:
factors = ['A', 'B', 'C']
factor_ranges=[[22.9,94.1],[13,23],[40.6,43]]
replication=4
center_point=True
#center_point=False
#randomize=True
randomize=False
factor_num=len(factors)
plan_arr = create_2level_full_factorial_design(factor_num, replication,randomize,center_point)
print(plan_arr)
label_list=['combo#']+factors
print(label_list)
df = pd.DataFrame(plan_arr, columns=label_list)
df.to_excel('full_factorial_design_catapult_coded.xlsx', index=True)


[[ 0.  0.  0.  0.]
 [ 1. -1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 3. -1.  1. -1.]
 [ 4. -1.  1.  1.]
 [ 5.  1. -1. -1.]
 [ 6.  1. -1.  1.]
 [ 7.  1.  1. -1.]
 [ 8.  1.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 1. -1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 3. -1.  1. -1.]
 [ 4. -1.  1.  1.]
 [ 5.  1. -1. -1.]
 [ 6.  1. -1.  1.]
 [ 7.  1.  1. -1.]
 [ 8.  1.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 1. -1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 3. -1.  1. -1.]
 [ 4. -1.  1.  1.]
 [ 5.  1. -1. -1.]
 [ 6.  1. -1.  1.]
 [ 7.  1.  1. -1.]
 [ 8.  1.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 1. -1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 3. -1.  1. -1.]
 [ 4. -1.  1.  1.]
 [ 5.  1. -1. -1.]
 [ 6.  1. -1.  1.]
 [ 7.  1.  1. -1.]
 [ 8.  1.  1.  1.]
 [ 0.  0.  0.  0.]]
['combo#', 'A', 'B', 'C']


If you want to run the experiment with real levels (not coded ones), run the following code to create another Excel spreadsheet.

In [3]:
real_arr=map_factors_to_ranges(factors, factor_ranges,plan_arr)
print(real_arr)
label_list=['combo#']+factors
print(label_list)
df = pd.DataFrame(real_arr, columns=label_list)
df.to_excel('full_factorial_design_catapult_real.xlsx', index=True)

[[ 0.  58.5 18.  41.8]
 [ 1.  22.9 13.  40.6]
 [ 2.  22.9 13.  43. ]
 [ 3.  22.9 23.  40.6]
 [ 4.  22.9 23.  43. ]
 [ 5.  94.1 13.  40.6]
 [ 6.  94.1 13.  43. ]
 [ 7.  94.1 23.  40.6]
 [ 8.  94.1 23.  43. ]
 [ 0.  58.5 18.  41.8]
 [ 1.  22.9 13.  40.6]
 [ 2.  22.9 13.  43. ]
 [ 3.  22.9 23.  40.6]
 [ 4.  22.9 23.  43. ]
 [ 5.  94.1 13.  40.6]
 [ 6.  94.1 13.  43. ]
 [ 7.  94.1 23.  40.6]
 [ 8.  94.1 23.  43. ]
 [ 0.  58.5 18.  41.8]
 [ 1.  22.9 13.  40.6]
 [ 2.  22.9 13.  43. ]
 [ 3.  22.9 23.  40.6]
 [ 4.  22.9 23.  43. ]
 [ 5.  94.1 13.  40.6]
 [ 6.  94.1 13.  43. ]
 [ 7.  94.1 23.  40.6]
 [ 8.  94.1 23.  43. ]
 [ 0.  58.5 18.  41.8]
 [ 1.  22.9 13.  40.6]
 [ 2.  22.9 13.  43. ]
 [ 3.  22.9 23.  40.6]
 [ 4.  22.9 23.  43. ]
 [ 5.  94.1 13.  40.6]
 [ 6.  94.1 13.  43. ]
 [ 7.  94.1 23.  40.6]
 [ 8.  94.1 23.  43. ]
 [ 0.  58.5 18.  41.8]]
['combo#', 'A', 'B', 'C']


In [4]:
#interactive input interface
# Create an IntRange widget for factor range
factor_A_range_widget = widgets.IntRangeSlider(
    value=[20, 80],
    min=0,
    max=100,
    step=1,
    description='A Range:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)
factor_B_range_widget = widgets.IntRangeSlider(
    value=[20, 80],
    min=0,
    max=100,
    step=1,
    description='B Range:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)
factor_C_range_widget = widgets.IntRangeSlider(
    value=[20, 80],
    min=0,
    max=100,
    step=1,
    description='C Range:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)
# Create text input for number of replication
replication_num_widget = widgets.IntText(
    value=3,
    description='Replication=',
    disabled=False
)
#
# Create dropdown for randomization
  #randomize_widget = widgets.Dropdown(
  #  options=[('Yes', True), ('No', False)],
  #  value=True,
 #   description='Randomize:',
#)
#

# Create checkbox for randomization
randomize_widget = widgets.Checkbox(
    value=True,
    description='Randomize:',
    disabled=False,
    indent=False
)
# Create checkbox for center point
center_point_widget = widgets.Checkbox(
    value=True,
    description='Center Point:',
    disabled=False,
    indent=False
)

# Display the widgets
display(factor_A_range_widget,factor_B_range_widget,factor_C_range_widget,replication_num_widget, randomize_widget, center_point_widget)
#while True:
  #try:
   # factor_num = int(factor_num_widget.value)
    #break
  #except ValueError:
    #print("Invalid input. Please enter an integer for the number of factors.")


IntRangeSlider(value=(20, 80), continuous_update=False, description='A Range:')

IntRangeSlider(value=(20, 80), continuous_update=False, description='B Range:')

IntRangeSlider(value=(20, 80), continuous_update=False, description='C Range:')

IntText(value=3, description='Replication=')

Checkbox(value=True, description='Randomize:', indent=False)

Checkbox(value=True, description='Center Point:', indent=False)

In [6]:
# creating spreadsheet for DOE
factors = ['A', 'B', 'C']
A_range=factor_A_range_widget.value
B_range=factor_B_range_widget.value
C_range=factor_C_range_widget.value
factor_ranges=[A_range,B_range,C_range]
#factor_ranges=[[22.9,94.1],[13,23],[40.6,43]]
factor_num = len(factors)
randomize = randomize_widget.value
center_point = center_point_widget.value
replication = replication_num_widget.value
plan_arr = create_2level_full_factorial_design(factor_num, replication,randomize,center_point)
label_list=['combo#']+factors
print(label_list)
print(plan_arr)
df = pd.DataFrame(plan_arr, columns=label_list)
df.to_excel('full_factorial_design_catapult_coded.xlsx', index=True)
real_arr=map_factors_to_ranges(factors, factor_ranges,plan_arr)
df = pd.DataFrame(real_arr, columns=label_list)
print(real_arr)
df.to_excel('full_factorial_design_catapult_real.xlsx', index=True)


['combo#', 'A', 'B', 'C']
[[ 0.  0.  0.  0.]
 [ 7.  1.  1. -1.]
 [ 6.  1. -1.  1.]
 [ 1. -1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 4. -1.  1.  1.]
 [ 8.  1.  1.  1.]
 [ 3. -1.  1. -1.]
 [ 5.  1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 3. -1.  1. -1.]
 [ 1. -1. -1. -1.]
 [ 6.  1. -1.  1.]
 [ 8.  1.  1.  1.]
 [ 7.  1.  1. -1.]
 [ 4. -1.  1.  1.]
 [ 5.  1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 0.  0.  0.  0.]
 [ 6.  1. -1.  1.]
 [ 4. -1.  1.  1.]
 [ 3. -1.  1. -1.]
 [ 8.  1.  1.  1.]
 [ 5.  1. -1. -1.]
 [ 1. -1. -1. -1.]
 [ 7.  1.  1. -1.]
 [ 2. -1. -1.  1.]
 [ 0.  0.  0.  0.]
 [ 6.  1. -1.  1.]
 [ 5.  1. -1. -1.]
 [ 1. -1. -1. -1.]
 [ 2. -1. -1.  1.]
 [ 4. -1.  1.  1.]
 [ 8.  1.  1.  1.]
 [ 3. -1.  1. -1.]
 [ 7.  1.  1. -1.]
 [ 0.  0.  0.  0.]]
[[ 0.  40.  51.5 54. ]
 [ 7.  60.  65.  15. ]
 [ 6.  60.  38.  93. ]
 [ 1.  20.  38.  15. ]
 [ 2.  20.  38.  93. ]
 [ 4.  20.  65.  93. ]
 [ 8.  60.  65.  93. ]
 [ 3.  20.  65.  15. ]
 [ 5.  60.  38.  15. ]
 [ 0.  40.  51.5 54. ]
 [ 3.  20.  65.  15. ]
 [ 1.  20.  38.  